// Code generated by cssGen. DO NOT EDIT.

package react

import "github.com/gopherjs/gopherjs/js"

// CSS defines CSS attributes for HTML components. Largely based on
// https://developer.mozilla.org/en-US/docs/Web/CSS/Reference
//
type CSS struct {
	o *js.Object

	Background      string
	BackgroundColor string
	Border          string
	Clear           string
	Color           string
	Display         string
	Float           string
	FontSize        string
	FontStyle       string
	FontWeight      string
	Height          string
	ListStyle       string
	Margin          string
	MaxHeight       string
	MinHeight       string
	Overflow        string
	Padding         string
	Resize          string
	Width           string
}

// TODO: until we have a resolution on
// https://github.com/gopherjs/gopherjs/issues/236 we define hack() below

func (c *CSS) hack() *CSS {
	if c == nil {
		return nil
	}

	o := object.New()

	o.Set("background", c.Background)
	o.Set("backgroundColor", c.BackgroundColor)
	o.Set("border", c.Border)
	o.Set("clear", c.Clear)
	o.Set("color", c.Color)
	o.Set("display", c.Display)
	o.Set("float", c.Float)
	o.Set("fontSize", c.FontSize)
	o.Set("fontStyle", c.FontStyle)
	o.Set("fontWeight", c.FontWeight)
	o.Set("height", c.Height)
	o.Set("listStyle", c.ListStyle)
	o.Set("margin", c.Margin)
	o.Set("maxHeight", c.MaxHeight)
	o.Set("minHeight", c.MinHeight)
	o.Set("overflow", c.Overflow)
	o.Set("padding", c.Padding)
	o.Set("resize", c.Resize)
	o.Set("width", c.Width)

	return &CSS{o: o}
}
