// Code generated by reactGen. DO NOT EDIT.

package react

// CaptionProps defines the properties for the <caption> element
type CaptionProps struct {
	ClassName               string
	DangerouslySetInnerHTML *DangerousInnerHTMLDef
	ID                      string
	Key                     string

	OnChange
	OnClick
	OnMouseDown
	OnMouseEnter
	OnMouseLeave
	OnMouseMove
	OnMouseOut
	OnMouseOver
	OnMouseUp

	Role  string
	Style *CSS
	Title string
}

func (c *CaptionProps) assign(v *_CaptionProps) {

	v.ClassName = c.ClassName

	v.DangerouslySetInnerHTML = c.DangerouslySetInnerHTML

	if c.ID != "" {
		v.ID = c.ID
	}

	if c.Key != "" {
		v.Key = c.Key
	}

	if c.OnChange != nil {
		v.o.Set("onChange", c.OnChange.OnChange)
	}

	if c.OnClick != nil {
		v.o.Set("onClick", c.OnClick.OnClick)
	}

	if c.OnMouseDown != nil {
		v.o.Set("onMouseDown", c.OnMouseDown.OnMouseDown)
	}

	if c.OnMouseEnter != nil {
		v.o.Set("onMouseEnter", c.OnMouseEnter.OnMouseEnter)
	}

	if c.OnMouseLeave != nil {
		v.o.Set("onMouseLeave", c.OnMouseLeave.OnMouseLeave)
	}

	if c.OnMouseMove != nil {
		v.o.Set("onMouseMove", c.OnMouseMove.OnMouseMove)
	}

	if c.OnMouseOut != nil {
		v.o.Set("onMouseOut", c.OnMouseOut.OnMouseOut)
	}

	if c.OnMouseOver != nil {
		v.o.Set("onMouseOver", c.OnMouseOver.OnMouseOver)
	}

	if c.OnMouseUp != nil {
		v.o.Set("onMouseUp", c.OnMouseUp.OnMouseUp)
	}

	v.Role = c.Role

	// TODO: until we have a resolution on
	// https://github.com/gopherjs/gopherjs/issues/236
	v.Style = c.Style.hack()

	v.Title = c.Title

}
