// Code generated by reactGen. DO NOT EDIT.

package react

// SelectProps are the props for a <select> component
type SelectProps struct {
	ClassName               string
	DangerouslySetInnerHTML *DangerousInnerHTMLDef
	ID                      string
	Key                     string

	OnChange
	OnClick
	OnMouseDown
	OnMouseEnter
	OnMouseLeave
	OnMouseMove
	OnMouseOut
	OnMouseOver
	OnMouseUp

	Role  string
	Style *CSS
	Title string
	Value string
}

func (s *SelectProps) assign(v *_SelectProps) {

	v.ClassName = s.ClassName

	v.DangerouslySetInnerHTML = s.DangerouslySetInnerHTML

	if s.ID != "" {
		v.ID = s.ID
	}

	if s.Key != "" {
		v.Key = s.Key
	}

	if s.OnChange != nil {
		v.o.Set("onChange", s.OnChange.OnChange)
	}

	if s.OnClick != nil {
		v.o.Set("onClick", s.OnClick.OnClick)
	}

	if s.OnMouseDown != nil {
		v.o.Set("onMouseDown", s.OnMouseDown.OnMouseDown)
	}

	if s.OnMouseEnter != nil {
		v.o.Set("onMouseEnter", s.OnMouseEnter.OnMouseEnter)
	}

	if s.OnMouseLeave != nil {
		v.o.Set("onMouseLeave", s.OnMouseLeave.OnMouseLeave)
	}

	if s.OnMouseMove != nil {
		v.o.Set("onMouseMove", s.OnMouseMove.OnMouseMove)
	}

	if s.OnMouseOut != nil {
		v.o.Set("onMouseOut", s.OnMouseOut.OnMouseOut)
	}

	if s.OnMouseOver != nil {
		v.o.Set("onMouseOver", s.OnMouseOver.OnMouseOver)
	}

	if s.OnMouseUp != nil {
		v.o.Set("onMouseUp", s.OnMouseUp.OnMouseUp)
	}

	v.Role = s.Role

	// TODO: until we have a resolution on
	// https://github.com/gopherjs/gopherjs/issues/236
	v.Style = s.Style.hack()

	v.Title = s.Title

	v.Value = s.Value

}
